services:
  backed:
    container_name: "backend"
    restart: always
    build: "./backend"
    ports:
      - 4000:4000
    external_links:
      - mongo

  frontend:
    container_name: "frontend"
    restart: always
    build: "./frontend-assements"
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    container_name: "mongo-server"
    ports:
      - 27017:27017

  mongo-express-app:
    container_name: "mongo-express"
    image: "mongo-express"
    ports:
      - "8083:8081"
